function point_pred = tracking_2d(points,t,res)
% TRACKING_2D: Track the given points in all frames based on the control
% meshes estimated by the groupwise registration algorithm
%
%   Input
%   ------------------
%   points       - Coordinates of the initial points
%   t            - Index of initial frame where the initial points lie in
%   res          - Structure of resulting parameters generated by the main
%                  function of the groupwise registration algorithm
%
%   Output
%   ------------------
%   point_pred   - Cell array of tracking results,that is the coordinates
%                  of the tracked points in all frames
%
%
% Copyright: Haiyang Chen, Chenxi Hu, SJTU 2022

% fprintf('Initial frame: %d\n',t)

Nt = size(res.mesh_x,3);

point_pred = cell(Nt,1);
point_pred{t} = points;

mesh_x_t = res.mesh_x(:,:,t);
mesh_y_t = res.mesh_y(:,:,t);
[inv_mesh_x_t,inv_mesh_y_t,okno] = invert_control_mesh(mesh_x_t,mesh_y_t,res.okno);

% Points in the reference space
points = move_points(points,inv_mesh_x_t,inv_mesh_y_t,okno);
for i = 1:Nt

    if i ~= t
%         fprintf('Frame %d is under process...\n',i)
        point_pred{i} = move_points(points,res.mesh_x(:,:,i),res.mesh_y(:,:,i),res.okno);
    end
    
end

end


